-- This SQL code was generated by scikit2sql (development version).
-- Copyright 2017

WITH linear_model_cte AS 
(SELECT "ADS"."KEY" AS "KEY", 6.420915373731375 * "ADS"."Feature_0" + 6.276623986230769 * "ADS"."Feature_1" + -0.31234956066172265 * "ADS"."Feature_2" + 6.853020437937982 * "ADS"."Feature_3" + 4.923858259770189 * "ADS"."Feature_4" + 0.22040005875851754 * "ADS"."Feature_5" + -0.05089264684651904 * "ADS"."Feature_6" + -0.6715831379825955 * "ADS"."Feature_7" + -0.05684829988679033 * "ADS"."Feature_8" + -0.8183175934515671 * "ADS"."Feature_9" + 3.2670604805 AS "Estimator" 
FROM "INPUT_DATA" "ADS")
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte