-- This SQL code was generated by scikit2sql (development version).
-- Copyright 2017

WITH linear_model_cte AS 
(SELECT "ADS"."KEY" AS "KEY", -0.005761172832421038 * "ADS"."Feature_0" + 0.00021859322996584476 * "ADS"."Feature_1" + 0.662571053994181 * "ADS"."Feature_2" + -0.016413161859054982 * "ADS"."Feature_3" + 1.13159519158 AS "Estimator" 
FROM freidman3 AS "ADS")
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte