-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : MLPRegressor
-- Dataset : diabetes
-- Database : mysql


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Code For temporary table TMP_20180417025014_VNK3LE_HL_1_relu_1 part 1/2. Create 


CREATE TEMPORARY TABLE `TMP_20180417025014_VNK3LE_HL_1_relu_1` (
	`KEY` BIGINT NOT NULL, 
	`NEUR_1_1` DOUBLE, 
	`NEUR_1_2` DOUBLE, 
	`NEUR_1_3` DOUBLE, 
	PRIMARY KEY (`KEY`)
)

 ENGINE=MEMORY

-- Code For temporary table TMP_20180417025014_VNK3LE_HL_1_relu_1 part 2/2. Populate

INSERT INTO `TMP_20180417025014_VNK3LE_HL_1_relu_1` (`KEY`, `NEUR_1_1`, `NEUR_1_2`, `NEUR_1_3`) SELECT `U`.`KEY`, `U`.`NEUR_1_1`, `U`.`NEUR_1_2`, `U`.`NEUR_1_3` 
FROM (WITH `IL` AS 
(SELECT `ADS`.`KEY` AS `KEY`, `ADS`.`Feature_0` AS `Feature_0`, `ADS`.`Feature_1` AS `Feature_1`, `ADS`.`Feature_2` AS `Feature_2`, `ADS`.`Feature_3` AS `Feature_3`, `ADS`.`Feature_4` AS `Feature_4`, `ADS`.`Feature_5` AS `Feature_5`, `ADS`.`Feature_6` AS `Feature_6`, `ADS`.`Feature_7` AS `Feature_7`, `ADS`.`Feature_8` AS `Feature_8`, `ADS`.`Feature_9` AS `Feature_9` 
FROM diabetes AS `ADS`), 
`HL_BA_1` AS 
(SELECT `IL`.`KEY` AS `KEY`, -0.0987538926681687 * `IL`.`Feature_0` + -0.4339065623754804 * `IL`.`Feature_1` + -0.5374082842930847 * `IL`.`Feature_2` + -0.6010115405869616 * `IL`.`Feature_3` + 0.2550635785651665 * `IL`.`Feature_4` + 0.5277834293468453 * `IL`.`Feature_5` + -0.26776326334951994 * `IL`.`Feature_6` + -0.05443802843830369 * `IL`.`Feature_7` + -0.021645205400586703 * `IL`.`Feature_8` + -0.23616087670164304 * `IL`.`Feature_9` + -0.317960748726666 AS `NEUR_1_1`, 0.13157963354729105 * `IL`.`Feature_0` + 0.008428149362459086 * `IL`.`Feature_1` + -0.42319252199292984 * `IL`.`Feature_2` + 0.3603013899419509 * `IL`.`Feature_3` + 0.18973106485278518 * `IL`.`Feature_4` + 0.508989934214923 * `IL`.`Feature_5` + -0.30340700032536594 * `IL`.`Feature_6` + -0.6490251054863544 * `IL`.`Feature_7` + 0.572676186022858 * `IL`.`Feature_8` + -0.09596365143936655 * `IL`.`Feature_9` + -0.4152095736844888 AS `NEUR_1_2`, 0.5101015531179828 * `IL`.`Feature_0` + -7.00734966839897 * `IL`.`Feature_1` + 14.591448850631465 * `IL`.`Feature_2` + 9.843105388161481 * `IL`.`Feature_3` + -15.396104007633946 * `IL`.`Feature_4` + 11.786287144476413 * `IL`.`Feature_5` + -7.32703010361668 * `IL`.`Feature_6` + -4.421285818795744 * `IL`.`Feature_7` + 24.807655833284542 * `IL`.`Feature_8` + 2.2268886808534667 * `IL`.`Feature_9` + 1.8703310591596813 AS `NEUR_1_3` 
FROM `IL`), 
`HL_1_relu` AS 
(SELECT `HL_BA_1`.`KEY` AS `KEY`, greatest(`HL_BA_1`.`NEUR_1_1`, 0.0) AS `NEUR_1_1`, greatest(`HL_BA_1`.`NEUR_1_2`, 0.0) AS `NEUR_1_2`, greatest(`HL_BA_1`.`NEUR_1_3`, 0.0) AS `NEUR_1_3` 
FROM `HL_BA_1`)
 SELECT `HL_1_relu_1`.`KEY`, `HL_1_relu_1`.`NEUR_1_1`, `HL_1_relu_1`.`NEUR_1_2`, `HL_1_relu_1`.`NEUR_1_3` 
FROM (SELECT `HL_1_relu`.`KEY` AS `KEY`, `HL_1_relu`.`NEUR_1_1` AS `NEUR_1_1`, `HL_1_relu`.`NEUR_1_2` AS `NEUR_1_2`, `HL_1_relu`.`NEUR_1_3` AS `NEUR_1_3` 
FROM `HL_1_relu`) AS `HL_1_relu_1`) AS `U`

-- Code For temporary table TMP_20180417025014_6NXMD3_OL_identity_1 part 1/2. Create 


CREATE TEMPORARY TABLE `TMP_20180417025014_6NXMD3_OL_identity_1` (
	`KEY` BIGINT NOT NULL, 
	`NEUR_3_1` DOUBLE, 
	PRIMARY KEY (`KEY`)
)

 ENGINE=MEMORY

-- Code For temporary table TMP_20180417025014_6NXMD3_OL_identity_1 part 2/2. Populate

INSERT INTO `TMP_20180417025014_6NXMD3_OL_identity_1` (`KEY`, `NEUR_3_1`) SELECT `U`.`KEY`, `U`.`NEUR_3_1` 
FROM (WITH `HL_BA_2` AS 
(SELECT `HL_1_relu_1`.`KEY` AS `KEY`, -0.7406266314274963 * `HL_1_relu_1`.`NEUR_1_1` + 0.5914624628458883 * `HL_1_relu_1`.`NEUR_1_2` + -0.07609467427374014 * `HL_1_relu_1`.`NEUR_1_3` + -0.2703387923227537 AS `NEUR_2_1`, -0.14939287998847917 * `HL_1_relu_1`.`NEUR_1_1` + 0.6651798218035635 * `HL_1_relu_1`.`NEUR_1_2` + -1.0153050387399647 * `HL_1_relu_1`.`NEUR_1_3` + -11.793370461844614 AS `NEUR_2_2`, 0.0033451177956580896 * `HL_1_relu_1`.`NEUR_1_1` + 0.4577680578691893 * `HL_1_relu_1`.`NEUR_1_2` + 7.680687163269137 * `HL_1_relu_1`.`NEUR_1_3` + 10.939461717287147 AS `NEUR_2_3`, 0.1110895592445846 * `HL_1_relu_1`.`NEUR_1_1` + -0.5047390334656465 * `HL_1_relu_1`.`NEUR_1_2` + -0.4066287638345377 * `HL_1_relu_1`.`NEUR_1_3` + -0.7964330424336139 AS `NEUR_2_4`, -0.6221508250552439 * `HL_1_relu_1`.`NEUR_1_1` + 0.4332117223794061 * `HL_1_relu_1`.`NEUR_1_2` + -0.6588746866292823 * `HL_1_relu_1`.`NEUR_1_3` + -0.5537916280920224 AS `NEUR_2_5` 
FROM `TMP_20180417025014_VNK3LE_HL_1_relu_1` AS `HL_1_relu_1`), 
`HL_2_relu` AS 
(SELECT `HL_BA_2`.`KEY` AS `KEY`, greatest(`HL_BA_2`.`NEUR_2_1`, 0.0) AS `NEUR_2_1`, greatest(`HL_BA_2`.`NEUR_2_2`, 0.0) AS `NEUR_2_2`, greatest(`HL_BA_2`.`NEUR_2_3`, 0.0) AS `NEUR_2_3`, greatest(`HL_BA_2`.`NEUR_2_4`, 0.0) AS `NEUR_2_4`, greatest(`HL_BA_2`.`NEUR_2_5`, 0.0) AS `NEUR_2_5` 
FROM `HL_BA_2`), 
`OL_BA` AS 
(SELECT `HL_2_relu`.`KEY` AS `KEY`, -0.10855329679472683 * `HL_2_relu`.`NEUR_2_1` + 2.7615450124834244 * `HL_2_relu`.`NEUR_2_2` + 4.419080267834583 * `HL_2_relu`.`NEUR_2_3` + 0.7008368421268144 * `HL_2_relu`.`NEUR_2_4` + -0.24897430202736764 * `HL_2_relu`.`NEUR_2_5` + 36.162498084674375 AS `NEUR_3_1` 
FROM `HL_2_relu`), 
`OL_identity` AS 
(SELECT `OL_BA`.`KEY` AS `KEY`, `OL_BA`.`NEUR_3_1` AS `NEUR_3_1` 
FROM `OL_BA`)
 SELECT `OL_identity_1`.`KEY`, `OL_identity_1`.`NEUR_3_1` 
FROM (SELECT `OL_identity`.`KEY` AS `KEY`, `OL_identity`.`NEUR_3_1` AS `NEUR_3_1` 
FROM `OL_identity`) AS `OL_identity_1`) AS `U`

-- Model deployment code

SELECT `OL_identity_1`.`KEY` AS `KEY`, `OL_identity_1`.`NEUR_3_1` AS `Estimator` 
FROM `TMP_20180417025014_6NXMD3_OL_identity_1` AS `OL_identity_1`