-- This SQL code was generated by scikit2sql (development version).
-- Copyright 2017

WITH linear_model_cte AS 
(SELECT "ADS"."KEY" AS "KEY", 33.50478918285365 * "ADS"."Feature_0" + 72.14052655676953 * "ADS"."Feature_1" + 89.86870927572618 * "ADS"."Feature_2" + 32.49980973104691 * "ADS"."Feature_3" + 52.51367789531343 * "ADS"."Feature_4" + 81.65660576150766 * "ADS"."Feature_5" + 31.978949733830884 * "ADS"."Feature_6" + 41.467313519285106 * "ADS"."Feature_7" + 79.5225274326346 * "ADS"."Feature_8" + 53.20224923784616 * "ADS"."Feature_9" + 1.52149740554 AS "Estimator" 
FROM "RandomReg_10" "ADS")
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte