-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : MLPRegressor
-- Dataset : diabetes
-- Database : pgsql


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Code For temporary table TMP_20221018185817_UMW3U0W_HL_1_relu_1 part 1. Create 


CREATE TEMPORARY TABLE "TMP_20221018185817_UMW3U0W_HL_1_relu_1" (
	"KEY" BIGINT NOT NULL, 
	"NEUR_1_1" FLOAT, 
	"NEUR_1_2" FLOAT, 
	"NEUR_1_3" FLOAT, 
	PRIMARY KEY ("KEY")
)

 ON COMMIT PRESERVE ROWS

-- Code For temporary table TMP_20221018185817_UMW3U0W_HL_1_relu_1 part 2. Populate

WITH "IL" AS 
(SELECT "ADS"."KEY" AS "KEY", CAST("ADS"."Feature_0" AS FLOAT) AS "Feature_0", CAST("ADS"."Feature_1" AS FLOAT) AS "Feature_1", CAST("ADS"."Feature_2" AS FLOAT) AS "Feature_2", CAST("ADS"."Feature_3" AS FLOAT) AS "Feature_3", CAST("ADS"."Feature_4" AS FLOAT) AS "Feature_4", CAST("ADS"."Feature_5" AS FLOAT) AS "Feature_5", CAST("ADS"."Feature_6" AS FLOAT) AS "Feature_6", CAST("ADS"."Feature_7" AS FLOAT) AS "Feature_7", CAST("ADS"."Feature_8" AS FLOAT) AS "Feature_8", CAST("ADS"."Feature_9" AS FLOAT) AS "Feature_9" 
FROM diabetes AS "ADS"), 
"HL_BA_1" AS 
(SELECT "IL"."KEY" AS "KEY", -0.09875264713539092 * "IL"."Feature_0" + -0.43390108973214586 * "IL"."Feature_1" + -0.5374015062357042 * "IL"."Feature_2" + -0.6010039603334983 * "IL"."Feature_3" + 0.25506036157757295 * "IL"."Feature_4" + 0.5277767726821677 * "IL"."Feature_5" + -0.2677598861872365 * "IL"."Feature_6" + -0.05443734183908972 * "IL"."Feature_7" + -0.021644932400615505 * "IL"."Feature_8" + -0.2361578981242828 * "IL"."Feature_9" + -0.317960748726666 AS "NEUR_1_1", 0.13157797400013987 * "IL"."Feature_0" + 0.008428043062484077 * "IL"."Feature_1" + -0.4231871844802503 * "IL"."Feature_2" + 0.36029684564331194 * "IL"."Feature_3" + 0.18972867187102294 * "IL"."Feature_4" + 0.5089835145837378 * "IL"."Feature_5" + -0.30340317360656077 * "IL"."Feature_6" + -0.6490169196617834 * "IL"."Feature_7" + 0.5726689631487684 * "IL"."Feature_8" + -0.09596244109854828 * "IL"."Feature_9" + -0.4152095736844888 AS "NEUR_1_2", 3.0354608710827855 * "IL"."Feature_0" + -14.455503601851442 * "IL"."Feature_1" + 31.61735078128364 * "IL"."Feature_2" + 19.724401574249864 * "IL"."Feature_3" + -96.21974748451687 * "IL"."Feature_4" + 72.0663708253842 * "IL"."Feature_5" + 21.200669659329446 * "IL"."Feature_6" + 5.383594401175625 * "IL"."Feature_7" + 76.2162067985537 * "IL"."Feature_8" + 5.125533151397957 * "IL"."Feature_9" + 3.7652383132111398 AS "NEUR_1_3" 
FROM "IL"), 
"HL_1_relu" AS 
(SELECT "HL_BA_1"."KEY" AS "KEY", greatest("HL_BA_1"."NEUR_1_1", 0) AS "NEUR_1_1", greatest("HL_BA_1"."NEUR_1_2", 0) AS "NEUR_1_2", greatest("HL_BA_1"."NEUR_1_3", 0) AS "NEUR_1_3" 
FROM "HL_BA_1")
 INSERT INTO "TMP_20221018185817_UMW3U0W_HL_1_relu_1" ("KEY", "NEUR_1_1", "NEUR_1_2", "NEUR_1_3") SELECT "T"."KEY", "T"."NEUR_1_1", "T"."NEUR_1_2", "T"."NEUR_1_3" 
FROM (SELECT "HL_1_relu_1"."KEY" AS "KEY", "HL_1_relu_1"."NEUR_1_1" AS "NEUR_1_1", "HL_1_relu_1"."NEUR_1_2" AS "NEUR_1_2", "HL_1_relu_1"."NEUR_1_3" AS "NEUR_1_3" 
FROM (SELECT "HL_1_relu"."KEY" AS "KEY", "HL_1_relu"."NEUR_1_1" AS "NEUR_1_1", "HL_1_relu"."NEUR_1_2" AS "NEUR_1_2", "HL_1_relu"."NEUR_1_3" AS "NEUR_1_3" 
FROM "HL_1_relu") AS "HL_1_relu_1") AS "T"

-- Code For temporary table TMP_20221018185817_UMW3U0W_HL_1_relu_1 part 3. Create Index 

CREATE INDEX "ix_TMP_20221018185817_UMW3U0W_HL_1_relu_1_KEY" ON "TMP_20221018185817_UMW3U0W_HL_1_relu_1" ("KEY")

-- Code For temporary table TMP_20221018185817_ILR49OY_OL_identity_1 part 1. Create 


CREATE TEMPORARY TABLE "TMP_20221018185817_ILR49OY_OL_identity_1" (
	"KEY" BIGINT NOT NULL, 
	"NEUR_3_1" FLOAT, 
	PRIMARY KEY ("KEY")
)

 ON COMMIT PRESERVE ROWS

-- Code For temporary table TMP_20221018185817_ILR49OY_OL_identity_1 part 2. Populate

WITH "HL_BA_2" AS 
(SELECT "HL_1_relu_1"."KEY" AS "KEY", -0.740617290280189 * "HL_1_relu_1"."NEUR_1_1" + 0.5914550030303211 * "HL_1_relu_1"."NEUR_1_2" + -0.3008587115192802 * "HL_1_relu_1"."NEUR_1_3" + -0.38542135838485336 AS "NEUR_2_1", -0.14939099577202336 * "HL_1_relu_1"."NEUR_1_1" + 0.6651714322286757 * "HL_1_relu_1"."NEUR_1_2" + -1.0606531673057698 * "HL_1_relu_1"."NEUR_1_3" + -14.01869468121295 AS "NEUR_2_2", 0.003345075605384864 * "HL_1_relu_1"."NEUR_1_1" + 0.4577622842726293 * "HL_1_relu_1"."NEUR_1_2" + 5.415432127395448 * "HL_1_relu_1"."NEUR_1_3" + 13.376846184048548 AS "NEUR_2_3", 0.11108815812835289 * "HL_1_relu_1"."NEUR_1_1" + -0.5047326674481184 * "HL_1_relu_1"."NEUR_1_2" + -0.4066236352324281 * "HL_1_relu_1"."NEUR_1_3" + -0.7964330424336139 AS "NEUR_2_4", -0.6221429781821264 * "HL_1_relu_1"."NEUR_1_1" + 0.4332062585001539 * "HL_1_relu_1"."NEUR_1_2" + -0.6588663765769616 * "HL_1_relu_1"."NEUR_1_3" + -0.5537916280920224 AS "NEUR_2_5" 
FROM "TMP_20221018185817_UMW3U0W_HL_1_relu_1" AS "HL_1_relu_1"), 
"HL_2_relu" AS 
(SELECT "HL_BA_2"."KEY" AS "KEY", greatest("HL_BA_2"."NEUR_2_1", 0) AS "NEUR_2_1", greatest("HL_BA_2"."NEUR_2_2", 0) AS "NEUR_2_2", greatest("HL_BA_2"."NEUR_2_3", 0) AS "NEUR_2_3", greatest("HL_BA_2"."NEUR_2_4", 0) AS "NEUR_2_4", greatest("HL_BA_2"."NEUR_2_5", 0) AS "NEUR_2_5" 
FROM "HL_BA_2"), 
"OL_BA" AS 
(SELECT "HL_2_relu"."KEY" AS "KEY", -0.26412117007236796 * "HL_2_relu"."NEUR_2_1" + 3.418755221735632 * "HL_2_relu"."NEUR_2_2" + 3.022224176433985 * "HL_2_relu"."NEUR_2_3" + 0.7008280028278233 * "HL_2_relu"."NEUR_2_4" + -0.24897116184081444 * "HL_2_relu"."NEUR_2_5" + 44.48510630944687 AS "NEUR_3_1" 
FROM "HL_2_relu"), 
"OL_identity" AS 
(SELECT "OL_BA"."KEY" AS "KEY", "OL_BA"."NEUR_3_1" AS "NEUR_3_1" 
FROM "OL_BA")
 INSERT INTO "TMP_20221018185817_ILR49OY_OL_identity_1" ("KEY", "NEUR_3_1") SELECT "T"."KEY", "T"."NEUR_3_1" 
FROM (SELECT "OL_identity_1"."KEY" AS "KEY", "OL_identity_1"."NEUR_3_1" AS "NEUR_3_1" 
FROM (SELECT "OL_identity"."KEY" AS "KEY", "OL_identity"."NEUR_3_1" AS "NEUR_3_1" 
FROM "OL_identity") AS "OL_identity_1") AS "T"

-- Code For temporary table TMP_20221018185817_ILR49OY_OL_identity_1 part 3. Create Index 

CREATE INDEX "ix_TMP_20221018185817_ILR49OY_OL_identity_1_KEY" ON "TMP_20221018185817_ILR49OY_OL_identity_1" ("KEY")

-- Model deployment code

SELECT "OL_identity_1"."KEY" AS "KEY", "OL_identity_1"."NEUR_3_1" AS "Estimator" 
FROM "TMP_20221018185817_ILR49OY_OL_identity_1" AS "OL_identity_1"