-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : SGDRegressor
-- Dataset : california_housing
-- Database : duck


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH linear_input AS 
(SELECT "ADS"."KEY" AS "KEY", CAST("ADS"."Feature_0" AS DOUBLE) AS "Feature_0", CAST("ADS"."Feature_1" AS DOUBLE) AS "Feature_1", CAST("ADS"."Feature_2" AS DOUBLE) AS "Feature_2", CAST("ADS"."Feature_3" AS DOUBLE) AS "Feature_3", CAST("ADS"."Feature_4" AS DOUBLE) AS "Feature_4", CAST("ADS"."Feature_5" AS DOUBLE) AS "Feature_5", CAST("ADS"."Feature_6" AS DOUBLE) AS "Feature_6", CAST("ADS"."Feature_7" AS DOUBLE) AS "Feature_7" 
FROM california_housing AS "ADS"), 
linear_model_cte AS 
(SELECT linear_input."KEY" AS "KEY", -131822431129.0826 * linear_input."Feature_0" + 454980884924.08374 * linear_input."Feature_1" + -331634823366.83093 * linear_input."Feature_2" + -71564091964.59036 * linear_input."Feature_3" + 241893109296.81226 * linear_input."Feature_4" + 229725165806.31506 * linear_input."Feature_5" + -128883820101.7921 * linear_input."Feature_6" + 148450542081.5134 * linear_input."Feature_7" + -2981165960.49865 AS "Estimator" 
FROM linear_input)
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte