-- This SQL code was generated by scikit2sql (development version).
-- Copyright 2017

WITH linear_model_cte AS 
(SELECT [ADS].[KEY] AS [KEY], 73.2020349990147 * [ADS].[Feature_0] + -19.738897689552147 * [ADS].[Feature_1] + -10.064723400161057 * [ADS].[Feature_2] + 4.9603387621480115 * [ADS].[Feature_3] + -44.77214260785363 * [ADS].[Feature_4] + 22.65138856648422 * [ADS].[Feature_5] + 3.6517170812313404 * [ADS].[Feature_6] + 51.48408379059403 * [ADS].[Feature_7] + 27.77192810489338 * [ADS].[Feature_8] + 30.756259329206056 * [ADS].[Feature_9] + 5.4604705988 AS linear_combination 
FROM [BinaryClass_10] AS [ADS])
 SELECT linear_model_cte.[KEY] AS [KEY], -linear_model_cte.linear_combination AS [Score_0], linear_model_cte.linear_combination AS [Score_1], CAST(NULL AS FLOAT(53)) AS [Proba_0], CAST(NULL AS FLOAT(53)) AS [Proba_1], CAST(NULL AS FLOAT(53)) AS [LogProba_0], CAST(NULL AS FLOAT(53)) AS [LogProba_1], CASE WHEN (linear_model_cte.linear_combination >= 0.0) THEN 1 ELSE 0 END AS [Decision] 
FROM linear_model_cte