-- This SQL code was generated by scikit2sql (development version).
-- Copyright 2017

WITH random_number_cte AS 
(SELECT [ADS].[KEY] AS [KEY], rand() AS uniform 
FROM [BinaryClass_500] AS [ADS]), 
multinomial_cte AS 
(SELECT random_number_cte.[KEY] AS [KEY], CASE WHEN (random_number_cte.uniform <= 0.477611940299) THEN 0 ELSE CASE WHEN (random_number_cte.uniform <= 1.0) THEN 1 END END AS multinomial_expr 
FROM random_number_cte), 
dummy_class_reg_cte AS 
(SELECT multinomial_cte.[KEY] AS [KEY], 0.477611940299 AS [Proba_0], CASE WHEN (0.477611940299 IS NULL OR 0.477611940299 > 0.0) THEN log(0.477611940299) ELSE -1.79769313486231e+308 END AS [LogProba_0], 0.522388059701 AS [Proba_1], CASE WHEN (0.522388059701 IS NULL OR 0.522388059701 > 0.0) THEN log(0.522388059701) ELSE -1.79769313486231e+308 END AS [LogProba_1], multinomial_cte.multinomial_expr AS [Decision] 
FROM multinomial_cte)
 SELECT dummy_class_reg_cte.[KEY] AS [KEY], CAST(NULL AS FLOAT(53)) AS [Score_0], CAST(NULL AS FLOAT(53)) AS [Score_1], dummy_class_reg_cte.[Proba_0] AS [Proba_0], dummy_class_reg_cte.[Proba_1] AS [Proba_1], dummy_class_reg_cte.[LogProba_0] AS [LogProba_0], dummy_class_reg_cte.[LogProba_1] AS [LogProba_1], dummy_class_reg_cte.[Decision] AS [Decision] 
FROM dummy_class_reg_cte