-- This SQL code was generated by sklearn2sql (development version).
-- Copyright 2018

-- Model : Ridge
-- Dataset : boston
-- Database : teradata


-- This SQL code can contain one or more statements, to be executed in the order they appear in this file.



-- Model deployment code

WITH linear_input AS 
(SELECT "ADS"."KEY" AS "KEY", CAST("ADS"."Feature_0" AS DOUBLE PRECISION) AS "Feature_0", CAST("ADS"."Feature_1" AS DOUBLE PRECISION) AS "Feature_1", CAST("ADS"."Feature_2" AS DOUBLE PRECISION) AS "Feature_2", CAST("ADS"."Feature_3" AS DOUBLE PRECISION) AS "Feature_3", CAST("ADS"."Feature_4" AS DOUBLE PRECISION) AS "Feature_4", CAST("ADS"."Feature_5" AS DOUBLE PRECISION) AS "Feature_5", CAST("ADS"."Feature_6" AS DOUBLE PRECISION) AS "Feature_6", CAST("ADS"."Feature_7" AS DOUBLE PRECISION) AS "Feature_7", CAST("ADS"."Feature_8" AS DOUBLE PRECISION) AS "Feature_8", CAST("ADS"."Feature_9" AS DOUBLE PRECISION) AS "Feature_9", CAST("ADS"."Feature_10" AS DOUBLE PRECISION) AS "Feature_10", CAST("ADS"."Feature_11" AS DOUBLE PRECISION) AS "Feature_11", CAST("ADS"."Feature_12" AS DOUBLE PRECISION) AS "Feature_12" 
FROM boston AS "ADS"), 
linear_model_cte AS 
(SELECT linear_input."KEY" AS "KEY", CAST(-0.092797905301555 AS DOUBLE PRECISION) * linear_input."Feature_0" + CAST(0.038348732210724 AS DOUBLE PRECISION) * linear_input."Feature_1" + CAST(-0.005696129838456 AS DOUBLE PRECISION) * linear_input."Feature_2" + CAST(2.296931450103133 AS DOUBLE PRECISION) * linear_input."Feature_3" + CAST(-8.234491142428583 AS DOUBLE PRECISION) * linear_input."Feature_4" + CAST(4.644280946244265 AS DOUBLE PRECISION) * linear_input."Feature_5" + CAST(-0.025699007698226 AS DOUBLE PRECISION) * linear_input."Feature_6" + CAST(-1.281004146208661 AS DOUBLE PRECISION) * linear_input."Feature_7" + CAST(0.256009052878334 AS DOUBLE PRECISION) * linear_input."Feature_8" + CAST(-0.012629982857975 AS DOUBLE PRECISION) * linear_input."Feature_9" + CAST(-0.919786485418035 AS DOUBLE PRECISION) * linear_input."Feature_10" + CAST(0.010843842193868 AS DOUBLE PRECISION) * linear_input."Feature_11" + CAST(-0.410637081456405 AS DOUBLE PRECISION) * linear_input."Feature_12" + CAST(25.178686937277092 AS DOUBLE PRECISION) AS "Estimator" 
FROM linear_input)
 SELECT linear_model_cte."KEY" AS "KEY", linear_model_cte."Estimator" AS "Estimator" 
FROM linear_model_cte